name: Docker Image Build

on:
  push:
    branches:
      - 'production'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag opencti-connector-template:$(date +%s)
    - name: Create GitHub Release
      uses: pipe-cd/actions-gh-release@v2.3.4
